### ISSUE TITLE
Can your plugin also report licence compliance issues?

### ISSUE THREAD

**Issue by chess-levin** [jenkinsci/dependency-track-plugin#130]
Hi folks, 
I found no answer in your docs on whether the denpency-track-jenkins-plugin can also be used to show license compliance breaches?
I'd would be great to have some more information about this topic.
Thank you for your great work!

**Comment by HagarJNode** [comment]
Is it the policy violations you have in mind? If so, that's what I made in pull request "Policy violations" - it handles the policies like vulnerabilities. Still waiting for being merged, but I got no clue if someone else checked my changes.

**Comment by dennisverheijen** [comment]
We also have need for the ability to fail the build on a policy violation, any updates?
