### ISSUE TITLE
dependencyTrackPublisher not recognized as a build step

### ISSUE THREAD

**Issue by marioja** [jenkinsci/dependency-track-plugin#143]
## Describe the bug
When creating a pipeline job, the dependencyTrackPublisher is not recognized as a build step.
## Environment

 - Plugin Version: 4.2.1-SNAPSHOT
 - Jenkins Version: 2.332.2
 - Java Version for Jenkins: 8
 - Type of Jenkins Job: declarative pipeline
 - Dependency-Track Version: 4.x
 
## To Reproduce
1. Create a pipeline job
2. click on the Pipeline Syntax link at the bottom
3. Click on the drop down for Sample Step
4. See that dependencyTrackPublisher does not appear

## Expected behavior
It should appear
## Additional context
If you try to run an existing job that contains it, you will get an error that the step is not know to the DSL.

**Comment by marioja** [comment]
I think an IT test should be created to detect such problems.

**Comment by sephiroth-j** [comment]
If the class is `final` or not has no influence. The build step is present and working. I am using it for almost 2 weeks now at work without problems with Jenkins v2.375.x.

Here a screenshot with a fresh Jenkins v2.332.2.

![1](https://user-images.githubusercontent.com/23166289/219761159-b5d4a4c8-5861-4fbc-a09e-f1ac9207dc79.png)
![2](https://user-images.githubusercontent.com/23166289/219761174-324bbada-cfb2-4fd7-a786-a29407a692ed.png)
![3](https://user-images.githubusercontent.com/23166289/219761199-42476256-ed6f-45c4-bca0-42c004fa8318.png)

It works as expected (DT was not running, resulting in a `ConnectException`).
