### ISSUE TITLE
Get Artifact from outside the workspace

### ISSUE THREAD

**Issue by ngocnn97** [jenkinsci/dependency-track-plugin#150]
## Is your feature request related to a problem? Please describe.
I'm having problems with saving the Artifact right in the workspace, which crashes some of the following gates in the pipeline, I tried saving /tmp/ but the plugin doesn't read

**Comment by sephiroth-j** [comment]
Then it's probably an issue with the file permissions. The artifact location is not limited to the workspace. The file must be readable by the user running the Jenkins job.

**Comment by ngocnn97** [comment]
i have set 777 permissions for the generated file, Jenkins user also has full /tmp read permissions, i have ```ls -l``` as well as ```cat``` file normally in jenkins, I think the problem is with Dtrack Plugin

**Comment by sephiroth-j** [comment]
Please file a proper bug report that includes the necessary information, log messages, and steps to reproduce this issue.
