### ISSUE TITLE
Error was: Input length = 1

### ISSUE THREAD

**Issue by eldoranstars** [jenkinsci/dependency-track-plugin#157]
## Describe the bug
From jenkins stage:
```
        stage('Dtrack') {
            steps {
                dependencyTrackPublisher artifact: "${APP_DIR}/${BOM_FILE}", 
                failedTotalCritical: 1, 
                failedTotalHigh: 1, 
                projectName: OCP_APP_NAME,
                projectVersion: "${params.APP_BRANCH}",
                synchronous: true
            }
        }
```
We get an error:
`[DependencyTrack] An error occurred processing artifact "/opt/jenkins/workspace/NDR_DTRACK/dtrack-dotnet6/dep-track/bom.xml". Error was: Input length = 1`

## Environment

 - Plugin Version:
` OWASP Dependency-Track Version 4.1.1`
 - Jenkins Version: 
`Jenkins 2.375`
 - Java Version for Jenkins:
```
openjdk 11.0.2 2019-01-15 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.2+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7-LTS, mixed mode, sharing)
```
 - Type of Jenkins Job: classic | declarative pipeline | scripted pipeline
`declarative pipeline `
 - Dependency-Track Version:
`Dependency-Track  v4.7.0 `

## Expected behavior
`Expect to upload bom file without errors.`

**Comment by sephiroth-j** [comment]
Please see #138
