### ISSUE TITLE
Link to Dependency-Track Server missing "?uuid=" for DT 3.x

### ISSUE THREAD

**Issue by msymons** [jenkinsci/dependency-track-plugin#17]
## Describe the bug
Release 3.0.0 of the plugin introduces new functionality to provide a link "Dependency-Track Project" from a Jenkins build to the matching project in the DT Server.

Clicking on the link display a blank screen.  This is because the URL is missing `?uuid=`.    eg:

```
https://dependency-track.foo.bar.com/projects/94bef94b-c33c-4064-9531-3810a43f1a16
```

should be:

```
https://dependency-track.foo.bar.com/projects/?uuid=94bef94b-c33c-4064-9531-3810a43f1a16
```
Note that the plugin is getting the value of the uuid correct (ie, `94bef94b-c33c-4064-9531-3810a43f1a16`)

## Environment

 - Plugin Version: 3.0.0
 - Jenkins Version:  2.263.1
 - Java Version for Jenkins: OpenJDK 1.8.0_262-b10
 - Type of Jenkins Job: classic and scripted pipeline
 - Dependency-Track Version: 3.7.1
 
## To Reproduce
1. Run a job in Jenkins that makes use of Dependency-Track plugin 
2. After build is complete, click on 'Dependency-Track Project'
3. See problem...  the project is not displayed.

## Expected behavior
Clicing on the link to  'Dependency-Track Project' should result in display of project on DT server.

## Additional context
I have not tested the functionality against DT v4.0.0 Beta, but I notice that the format of the URL does *not* include the `?uuid=`.  In other words, it looks like the link from Jenkins would work with this version of DT.

Perhaps the plugin could cater for both variants of the URL by using the `x-powered-by` header returned by DT server?

**Comment by sephiroth-j** [comment]
`/projects/:uuid` is the preferred url pattern for dtrack 3.8 and newer.

**Comment by sephiroth-j** [comment]
The plugin will use the legacy pattern `/project/?uuid=:uuid`. DTrack 3.8+ redirects to the new url `/projects/:uuid`.

**Comment by msymons** [comment]
Tested using v3.0.1 and looking good!
