### ISSUE TITLE
Report does not render correctly in Firefox

### ISSUE THREAD

**Issue by msymons** [jenkinsci/dependency-track-plugin#18]
## Describe the bug
The "Dependency Track Report" that is displayed within Jenkins seems to render fine using Chrome Browser & Microsoft Edge (tested both with v87) but does not render correctly when using Firefox (tested with v83.0)

![image](https://user-images.githubusercontent.com/4938718/101289915-45a7b280-37f7-11eb-92e6-54fc3b4f12b7.png)

## Environment

 - Plugin Version: 3.0.0
 - Jenkins Version:  2.263.1
 - Java Version for Jenkins: OpenJDK 1.8.0_262-b10
 - Type of Jenkins Job: classic and scripted pipeline
 - Dependency-Track Version: 3.7.1
 - Browser: Firefox 83.0
 
## To Reproduce
1. Run a job in Jenkins that makes use of Dependency-Track plugin 
2. After build is complete, click on 'Dependency-Track Report' whilst using Firefox browser
3. Report renders per screenshot above
4. View the report using either Chrome or Edge browser...  rendering seems fine.

## Expected behavior
Report should render correctly on Firefox as well as on Chrome or Edge (did not test with other browsers).

**Comment by sephiroth-j** [comment]
confirmed ... the preload keyword for the `rel` attribute of the `<link>` element [is still experimental in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1583604).

**Comment by msymons** [comment]
Tested using v3.0.1 and looking good!
