### ISSUE TITLE
Using the dependency-track-plugin behind an (authenticating) proxy

### ISSUE THREAD

**Issue by savek-cc** [jenkinsci/dependency-track-plugin#181]
## Is your feature request related to a problem? Please describe.
In our setup, Jenkins is running on premise - so that the build agents need to go through an authenticating proxy in order to access the DependencyTrack instance hostet in the cloud.
While the jenkins agents/build workers can access the DependencyTrack API using the default system proxy, the dependency-track-plugin apparently does not support using a proxy for the SBOM upload. It tries to do a direct connection - and in our case fails because it can not perform a DNS resolution (as any allowed traffic out of the Jenkins network is via a http/s proxy.

## Describe the solution you'd like
Make the plugin either check for (and use) the default system proxy - or use the jenkins proxy configuration.

## Additional context
See https://github.com/jenkinsci/dependency-track-plugin/blob/e7e4409570ee0d2eb31ba7ade5ecedb5b817f436/src/main/java/org/jenkinsci/plugins/DependencyTrack/ApiClient.java#L95C58-L95C68 (no proxy config)
vs. proxy usage in a different plugin
https://github.com/jenkinsci/oic-auth-plugin/blob/742fe576f1d406cf996fe5469a88e1940d963838/src/main/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactory.java#L27

**Comment by sephiroth-j** [comment]
The next version will use the Jenkins proxy. Thank you for the code example.
