### ISSUE TITLE
Explanation of upload error "Error was: Input length = 1

### ISSUE THREAD

**Issue by troy256** [jenkinsci/dependency-track-plugin#187]
## Describe the bug
We are building the SBOM manually in our Jenkins pipeline with cdxgen and then using the plugin to upload to Dependency Track.  It is working successfully in another job, for some reason we are getting this error:

![image](https://github.com/jenkinsci/dependency-track-plugin/assets/48829375/42c82f11-b616-4911-8d7f-e36a5d388e90)

Earlier in the pipeline we can see bom.json is generated, is a non-zero file size and sitting in the same directory referenced above:
![image](https://github.com/jenkinsci/dependency-track-plugin/assets/48829375/99d886bd-3803-4a95-891b-0e447786e840)

Can you provide guidance on troubleshooting this error?

## Environment

 - Plugin Version: 4.3.1
 - Type of Jenkins Job: pipeline

**Comment by sephiroth-j** [comment]
Please see #138
