### ISSUE TITLE
Prevent build from failing if error occurs

### ISSUE THREAD

**Issue by giacgbj** [jenkinsci/dependency-track-plugin#20]
Could you add an option in global, per-job and pipeline configurations to prevent the build from failing if an error occurs for whatever reason, for example during the communication with the Dependency-Track instance?
Failing a long build almost completed is very frustrating.

If you want to elaborate on it, you could add the option to select how to mark the build: success, unstable or failure (default, now).

**Comment by clausfod** [comment]
For async setup jobs this is "must have". For sync jobs it could be nice that the build did not fail, but instead gave the possibility to be unstable

**Comment by sephiroth-j** [comment]
Failing the build job if something is wrong with your build environment is a common behavior and it is intended (#9). It is also a signal (to you or Jenkins admin) that there is something abnormal and that needs your attention. If you want to ignore errors and make the job go on, use a pipeline job, wrap the `dependencyTrackPublisher` call in a try-catch block and do whatever makes you happy when an exception occurred.

**Declarative Pipeline example**
```groovy
pipeline {
    agent any

    stages {
        stage('dependencyTrackPublisher') {
		steps {
		        withCredentials([string(credentialsId: '506ed685-4e2b-4d31-a44f-8ba8e67b6341', variable: 'API_KEY')]) {
				script {
					try {
						dependencyTrackPublisher artifact: 'target/bom.xml', projectName: 'my-project', projectVersion: 'my-version', synchronous: true, dependencyTrackApiKey: API_KEY
					} catch (e) {
						echo 'failed'
					}
				}
			}
		}
        }
    }
}

```

**Scripted Pipeline example**: see README

**Comment by clausfod** [comment]
Thanks for that input. There is a lot of plugins for Jenkins supporting returning a response code when used, IMHO that would be much cleaner as this leaves the pipelines "in good shape" as you are able to create all you pipeline logic without a lot of try catches on different plugins.

It could be as simple as returning the HTTP code.

**Comment by rvsoni** [comment]
Hi @giacgbj 

I face the same issue, I fix the code on my fork (https://github.com/rvsoni/dependency-track-plugin/commit/eee42595df00ebe39b10447be02bfdb2400e4a55)

I introduced an option on the global config advance section, also on job config, that can help you to just upload a BOM and not wait for the result, this would mark build success. 

Pl. build this code and test it, Pl. let me know if there are any improvements, 

Ravi

**Comment by rvsoni** [comment]
It prints the below logs on Jenkins and does not wait to collect the result. ```

Waiting for Jenkins to finish collecting data
channel stopped
[DependencyTrack] Publishing artifact to Dependency-Track - https://dtrack.example.com
[DependencyTrack] Not waiting for project analysis result.
[JaCoCo plugin] Collecting JaCoCo coverage data...

Ravi
