### ISSUE TITLE
Fails if Dependencey Track API server returns Not Modified

### ISSUE THREAD

**Issue by HagarJNode** [jenkinsci/dependency-track-plugin#219]
## Describe the bug
If one has projects that with no modifications the API server will respond with a http status 304 when calling patchProject in the ProjectResource. The ApiClient updateProject in this plugin fails when the respons is not 200 and blocks builds when it happens.

## Environment

 - Plugin Version: 4.76
 - Jenkins Version: 2.426.2
 - Java Version for Jenkins: 17.0.9
 - Type of Jenkins Job: declarative pipeline
 - Dependency-Track Version: 4.10.0
 
## Expected behavior

Should accept getting 304 as well as 200.

## Additional context

10:59:59.558  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 0534db0c-5720-4d62-98db-2437527c2419
10:59:59.558  org.jenkinsci.plugins.DependencyTrack.ApiClientException: An error occurred while updating project with id "1d6e9e71-8f91-4892-8116-6723cd53cdee" - HTTP response code: 304 Not Modified

I could surely create a fix and a pull request to fix this, but I already have this https://github.com/jenkinsci/dependency-track-plugin/pull/122 and nothing has happened - no feedback, so I'm not sure that help is welcomed.

Work around:
Add tags to the projectProperties, as there is a bug in the API server that checks for modifications in collections of a project.

**Comment by sephiroth-j** [comment]
First of all, there is no version 4.76 of this plugin.

[The status code 304 is only used in the PATCH variant](https://github.com/DependencyTrack/dependency-track/blob/fcb8e784d9b208de5ab755a979a48f2535f3c390/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java#L416), which is only used in the current, unreleased development version of the plugin. [The status code is also not documented in the API description](https://github.com/DependencyTrack/dependency-track/blob/5c2a85547114b56ba9214f34083c41949d053622/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java#L339-L341). In addition, the status 304 is used incorrectly here. [The code is intended for GET and HEAD and only if it is a conditional request](https://www.rfc-editor.org/rfc/rfc9110.html#name-304-not-modified). However, I understand why it is used in this case and will adjust it in the plugin.

**Comment by HagarJNode** [comment]
Sorry, I wrote the org.jenkins-ci.plugins version instead of the version of the plugin - my fault.

Yes, I noted that the documentation of Dependency Track didn't have all the respons codes, as I was searching for the reason for the fail.

Glad that you're taking care for it in the plugin.

**Comment by sephiroth-j** [comment]
No problem, thanks for the tip.
