### ISSUE TITLE
Allow parentname and parentversion to be used during upload

### ISSUE THREAD

**Issue by Andreas-Hujber** [jenkinsci/dependency-track-plugin#261]
Currently the plugin only allows the usage of parentuuid to define the parent of a project and only using an update. This was the only possible way when this feature was implemented for DT 4.7.+. With DT 4.8.0 the api was extended to allow setting the parentName and parentVersion during the upload (DependencyTrack/dependency-track/issues/2412). This will make writing pipelines easier.

**Comment by sephiroth-j** [comment]
A good improvement to the original implementation of #139. Since version 4.9 is now the minimum requirement, this is also possible. Thanks for the hint.
