### ISSUE TITLE
Job still successful when policies violated

### ISSUE THREAD

**Issue by rizziemma** [jenkinsci/dependency-track-plugin#284]
### Describe the bug

Trying the latest feature to set pipelines in states UNSTABLE or FAILURE is not working for us currently.

With 4 policies failure, the pipeline is still ending with state SUCCESSFUL :
![Image](https://github.com/user-attachments/assets/29d06e5e-4297-42a9-8020-23e07191a26f)
![Image](https://github.com/user-attachments/assets/5ae5bb3e-0e2c-41ba-b346-01ffbfdf91ab)
![Image](https://github.com/user-attachments/assets/4a0f7985-cfab-4827-82f7-06664146f199)

### Plugin Version

5.1.0

### Jenkins Version

2.462.3

### Java Version for Jenkins

 21.0.4

### Type of Jenkins Job

declarative pipeline

### Dependency-Track Version

4.11.3

### Steps to reproduce the behavior

1. configure policies 
![Image](https://github.com/user-attachments/assets/46dde083-0ea7-4b0b-affc-9831a74f9e9a)

2. send a sbom with known vulnerabilities to fail policies
```
dependencyTrackPublisher(artifact: sbomPath, 
            projectName: repository,
            projectVersion: tag, 
            synchronous: true, 
            dependencyTrackApiKey: API_KEY
        )
```

### Expected behavior

The pipeline should end with FAILURE

**Comment by sephiroth-j** [comment]
Enabling `synchronous` will not automatically cause the build to fail if policy violations occur. You must also enable either one of `failOnViolationFail` or `warnOnViolationWarn` to have this happen. The former will cause a build to fail, the latter will mark it as unstable.

**Comment by rizziemma** [comment]
Thank you for your time @sephiroth-j I changed my pipeline and it works as expected now :
```
dependencyTrackPublisher(artifact: sbomPath, 
            projectName: repository,
            projectVersion: tag, 
            synchronous: true, 
            dependencyTrackApiKey: API_KEY,
            warnOnViolationWarn: true,
            failOnViolationFail: true
        )
```
This is not mentionned in the documentation [here](https://plugins.jenkins.io/dependency-track/#plugin-content-policy-violations) so may this post will help anyone confused like me
