### ISSUE TITLE
treshold is not working in declarative pipeline

### ISSUE THREAD

**Issue by aleixvilaseca** [jenkinsci/dependency-track-plugin#287]
Hello, the tresholds are not working when the dependency track updates the dependencies. It should return unstable or failed, however it shows success. In the plugin documentation, it seems that if you have synchronous to true, the pipeline should already fail in case it finds any critical vulnerability. I add config references. Thanks in advance.

pipeline >>

![Image](https://github.com/user-attachments/assets/603aa82f-8f9d-42f6-8833-ba6b6200cc45)

`def runDependencyTrackAnalysis() {
    withCredentials([string(credentialsId: 'dtrack-apikey', variable: 'DTRACK_API_KEY')]) {
        def dependencyTrackScan = new DependencyTrackScan(this, "${env.WORKSPACE}/target", 'my-url', DTRACK_API_KEY, 'my-project', 'project-version')
        dependencyTrackScan.run()
    }
}`

class >>

![Image](https://github.com/user-attachments/assets/8620dd45-e0a4-4d06-b104-56826a95ca01)

![Image](https://github.com/user-attachments/assets/a199e0ba-d3ef-4d76-88c3-cee115664733)
![Image](https://github.com/user-attachments/assets/af67969f-bbd9-4150-8068-3beb02973cec)

**Comment by sephiroth-j** [comment]
You have to define thresholds. The readme is quite clear about this.
