### ISSUE TITLE
Addition of creating tags, classifier, swid tag id to Jenkins Plugin for Declarative Pipeline Automation

### ISSUE THREAD

**Issue by aejazuddinam** [jenkinsci/dependency-track-plugin#50]
Hi Ronny,
With the current functionality of Jenkins pipeline, we could create project,version and upload bom to DT , but would like enhancement on more to create new tags attached to project, create Classifier, Add SWID tag id all this with the DTPublisher. 

Current functionality....
dependencyTrackPublisher artifact: 'target/bom.xml', projectName: 'my-project', projectVersion: 'my-version', synchronous: true, dependencyTrackApiKey: API_KEY
...

This would help on complete automation with managing multiple instances, without moving to UI dashboard.

**Comment by sephiroth-j** [comment]
Hello @aejazuddinam , thanks for your suggestions.

- The creation of tags is already tracked at #12 .
- The classifier is imported by DTrack from the BOM - for Java and Maven you can set it as follows `mvn -DprojectType=application org.cyclonedx:cyclonedx-maven-plugin:2.5.2:makeBom`.
- Setting the SWID could be done in the same call that is required for setting tags. Do you have an example of such a tag for me and how it looks like in the UI?

**Comment by aejazuddinam** [comment]
Thanks Ronny,
SWID Tag ID can be seen at the bottom , in the Identity tab just next to General Tab of Project Details.

Also do we have any examples for sending all notification emails and sending/capturing a project vulnerability report from DT Plugin ?  I want to configure it in my declarative pipeline for automation

**Comment by sephiroth-j** [comment]
>     * The classifier is imported by DTrack from the BOM - for Java and Maven you can set it as follows `mvn -DprojectType=application org.cyclonedx:cyclonedx-maven-plugin:2.5.2:makeBom`.

I noticed that DT has a bug that ignores this value for projects being auto-created during BOM upload. I made a PR to fix this - DependencyTrack/dependency-track/pull/1341
