### ISSUE TITLE
New findings threashold should be compute using old versions

### ISSUE THREAD

**Issue by guillomep** [jenkinsci/dependency-track-plugin#58]
## Describe the bug
When using the plugin to check vulnerabilities in our dependencies, there are to threshold, the total vulnerabilities and the new findings ones. It seems that the new findings does not take care of the project version.
For example:
* DT found 10 vulnerabilities in version 1.0.0
* DT found 1 more vulnerability in version 1.0.1

New findings should be 1, but it is not the case because our thresholds set to 5 failed the build when building version 1.0.1

## Environment

 - Plugin Version: 4.0.0
 - Jenkins Version: 2.303.2 (LTS)
 - Java Version for Jenkins: 11.0.12
 - Type of Jenkins Job: Scripted pipeline
 - Dependency-Track Version: 4.3.6
 
## To Reproduce
1. Upload a BOM with vulnerabilities and project version 1.0.0
2. Set threshold less than the number of vulnerabilities for new findings
3. Upload the same BOM and project version 1.0.1

## Expected behavior
The new findings should count new vulnerabilities between two versions of the same project

**Comment by sephiroth-j** [comment]
@guillomep , did your build job with the run of the analyses of version 1.0.1 had a previous run? Let's say you have a job "foo" with build run number 2 which was for used version 1.0.1 and previous run number 1 for version 1.0.1? If so, would you share the build.xml (located at `<jenkins_home>/jobs<job-name>/builds/<build-number>`) of both runs for further analyzing the bug? If you have concerns about the found vulnerabilities, we can find another way to share these files with me (email+ pgp).

> It seems that the new findings does not take care of the project version.

That is correct. The difference is calculated based on the result of the previous build run of the same job. This is also documented in the [readme ](/jenkinsci/dependency-track-plugin#thresholds )and in [the help of the "New Findings" section](/jenkinsci/dependency-track-plugin/blob/master/src/main/webapp/help-thresholds-new.html).

> If the number of new findings equals or is greater **than the previous builds finding** for any one of the severities, the
