### ISSUE TITLE
Analysis result information not shown when CSRF Protection is turned off

### ISSUE THREAD

**Issue by dalikrisz** [jenkinsci/dependency-track-plugin#73]
## Describe the bug
"Dependency-Track Trend", "Dependency Analysis Summary" and "Dependency-Track Report" fields are empty when the CSRF Protection is turned off in Jenkins security settings. 
_getFindingsJson_ and _getSeverityDistributionTrend_ returns HTTP 500 when called, the only logged message is a SecurityException (failed to pass the crumb test).

## Environment
 - Plugin Version: 4.0.0 (the problem was not present in 3.1.1)
 - Jenkins Version: 2.289.2
 - Java Version for Jenkins: openjdk 11.0.13
 - Dependency-Track Version: 4.3.4
 
## To Reproduce
1. Turn off "CSRF Protection" (Jenkins/Configure Global Security) - set a System property with name "hudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION" and value "true".
2. Navigate to a job/build where the Dependency Track plugin was executed, click on "Dependency-Track Report". 
3. The report is empty.
4. In the Jenkins log you can see an error message regarding the crumb test, detaild in "Additional context".

## Expected behavior
Dependency-Track analysis results should be shown even when the CSRF protection is turned off.

## Additional context
The plugin works as expected as soon as I enable the CSRF protection.

Screenshots showing the empty fields:
![image](https://user-images.githubusercontent.com/18336696/148977898-e8b42fcd-50a0-4f4e-af01-2b1604af98c0.png)
![image](https://user-images.githubusercontent.com/18336696/148977946-139878de-3d04-4d4a-88e8-a31a488c98ac.png)
![image](https://user-images.githubusercontent.com/18336696/148978211-68cfbace-9236-4516-a660-33710a6cd916.png)

The only log generated for the issue:
> Jan 11, 2022 3:43:48 PM WARNING hudson.init.impl.InstallUncaughtExceptionHandler handleException
> Caught unhandled exception with ID <exception_guid>
> java.lang.SecurityException: Request failed to pass the crumb test (try clearing your cookies)
> 	at org.kohsuke.stapler.CrumbIssuer.validateCrumb(CrumbIssuer.java:46)
> 	at hudson.security.csrf.CrumbIssuer$1.validateCrumb(CrumbIssuer.java:182)
> 	at org.kohsuke.stapler.MetaClass$JavaScriptProxyMethodDispatcher.doDispatch(MetaClass.java:620)
> 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
> 	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:457)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:834)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
> 	at org.kohsuke.stapler.Stapler.service(Stapler.java:201)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
> 	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
> 	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:112)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:60)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:211)
> 	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
> 	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:121)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at hudson.plugins.locale.LocaleFilter.doFilter(LocaleFilter.java:42)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:64)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:117)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
> 	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
> 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
> 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
> 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
> 	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
> 	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
> 	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
> 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
> 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
> 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
> 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by sephiroth-j** [comment]
I'm not sure I share the opinion on the expected behavior. Running Jenkins without CSRF protection is not supported. I think it will depend on how easy this will be to fix.

To quote from Jenkins/Configure Global Security
> That option should be considered unsupported and its use should be limited to working around compatibility problems until they are resolved.

**Comment by sephiroth-j** [comment]
okay, can be fixed relatively easily

**Comment by sephiroth-j** [comment]
@dalikrisz: will be fixed with the next release. You can try the dev build https://github.com/jenkinsci/dependency-track-plugin/suites/4901742718/artifacts/140850722 in the meantime.

**Comment by dalikrisz** [comment]
Thank you for your quick response and solution.

I agree with you, turning off CSRF protection is not a good choice, we are in the process of turning it back on.
In the meantime, this fix will be very appreciated.
