### ISSUE TITLE
jenkins result GUI not available

### ISSUE THREAD

**Issue by ja2081** [jenkinsci/dependency-track-plugin#84]
## Environment

 - Plugin Version: 5.1.2
 - Jenkins Version:  2.289
 - Java Version for Jenkins: jdk11
 - Type of Jenkins Job: apple swift 
 - Dependency-Track Version: none
 
## To Reproduce
1. Go to '...' project job after successful scan and publish
4. See the dep dependency-check trend graph with zero vulnerability, and dependency-check-report.xml can be found in the archive with hundreds lines of data. However, not seeing a link to the result GUI report page on anywhere of the jenkins job. 
![Screen Shot 2022-03-03 at 4 02 27 PM](https://user-images.githubusercontent.com/46178145/156652533-c855c572-2435-4cd4-a671-4a8c67a6d94d.png)

## Additional context
Add any other context about the problem here (screenshots, logs, etc.).

**Comment by sephiroth-j** [comment]
This is the issue tracker for the Dependency-**Track** Plugin. You are reporting an issue for [the Dependency-**Check** Plugin](https://plugins.jenkins.io/dependency-check-jenkins-plugin/). Please [report an issue in its own issue tracker using this link](https://www.jenkins.io/participate/report-issue/redirect/#18029).
