### ISSUE TITLE
ProjektId is overridden on new Project with synchronous result 

### ISSUE THREAD

**Issue by m-hruby** [jenkinsci/dependency-track-plugin#98]
## Describe the bug

When uploading result to Depency track (using projectName and projectVersion each time with different version and with synchronous result) the  ProjektId is overridden.

After the upload the Project id is now pinned to that Project so new version are ignored.   

## Environment

 - Plugin Version: 4.1.1

## To Reproduce
1. Configure Plugin with projectName and projectVersion (ignore ProjectId)
2. Upload first version (now the Project id should be configured)
3. Upload second version
4. Result is published to the first Project

## Expected behavior

Plugging configured with projectName and projectVersion should keep this setting and not use the projectId in further request.  

## Additional context

i think this is the broken part:

`projectId = apiClient.lookupProject(effectiveProjectName, effectiveProjectVersion).getUuid();`

**Comment by sephiroth-j** [comment]
Multiple calls using sync mode are not supported at this time.

**Comment by sephiroth-j** [comment]
If you would like to continue using the sync mode for different projects (_names and/or versions_) in one build job although it does not make any sense, you can set `projectId` to an empty string upon each invocation.

**Comment by m-hruby** [comment]
My use-case is one job for a project with different branches (versions). And it is not an option to update the job manually after each invocation. 

If this this it not supported than it should not  be possible to save this setting via UI in the plugging. This is what not make sense to my. If a save some setting the setting (with just name, version and `projectId` as empty string) this setting should persist. But after a build the projectId is overridden. Easy fix for that would be not set the projectId globally in this class.

**Comment by sephiroth-j** [comment]
I now understand what you actually mean and where the problem lies. I will take care of it. By the way, the information about Jenkins version and job type, which you have withheld so far, is requested at the beginning with good reason.
